"""rename value to amount

Revision ID: 61b909c4f859
Revises: a5f0ab24ccc4
Create Date: 2023-02-15 15:23:35.202881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b909c4f859'
down_revision = 'a5f0ab24ccc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('amount', sa.Float(), nullable=False))
    op.drop_column('transactions', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('value', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'amount')
    # ### end Alembic commands ###
