"""refactoring balance and value type to float

Revision ID: a5f0ab24ccc4
Revises: 3b9c6b23c5cb
Create Date: 2023-02-12 18:13:33.900687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f0ab24ccc4'
down_revision = '3b9c6b23c5cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
